config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: 'devise', controllers: { registrations: 'registrations' }
  resources :users

   root 'posts#index'
   resources :posts do
     shallow  do
       resources :comments, only: [:create]
     end
     member do
       put "vote", to: "posts#vote"
     end
   end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    current_user ||= User.new
    if current_user.role?(User::ADMIN_ROLE)
      admin_ability
    elsif current_user.role?(User::MODERATOR_ROLE)
      moderator_ability(current_user)
    else
      user_ability(current_user)
    end
  end

  def moderator_ability(current_user)
    can :read, [User, Comment]
    can [:read, :manage], Post
    can :manage, [Comment], user_id: current_user.id
  end

  def admin_ability
    can :manage, :all
  end

  def user_ability(current_user)
    can :read, [User, Comment, Post]
    can :manage, [Comment, Post], user_id: current_user.id
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, PictureUploader
  validates :title, :content, :image, presence: true
  has_many :comments
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  ROLES = [ADMIN_ROLE = :admin, MODERATOR_ROLE = :moderator, USER_ROLE = :user].freeze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :age, numericality: {greater_than: 0}
  validates :email, email_format: { :message => 'is not looking good' }
  validates :name, :last_name,  length: { in: 0..255, allow_blank: false }
  before_save :set_role_default

  def role?(user_role)
    role == user_role.to_s
  end

  private
  def set_role_default
    self.role ||= User::USER_ROLE.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!
load_and_authorize_resource

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to @post
    else
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:show, :edit, :destroy, :update]
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource :only => :vote
  protect_from_forgery except: :show

  def index
    @posts = Post.all
  end

  def show
     @comments = Comment.where(post: @post).paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to @post
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post was successfully destroyed.'
    redirect_to posts_url
  end

def vote
  if current_user.voted_up_on? @post
    @post.downvote_by current_user
  else
    @post.upvote_by current_user
  end
  respond_to do |format|
   format.js   { render :layout => false }
  end
end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :image, :content, :user)
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:age, :name, :last_name, :username, :email, :password) }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if not_change_password?
        params[:user].delete(:password)
      end
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:age, :name, :last_name, :username,
      :email, :password, :role)
  end

  def not_change_password?
      params[:user][:password].blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    { success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info',
      warning: 'alert-warning',
      }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/comments/_comment.slim
.media
  p.small.pull-right = comment.created_at.to_formatted_s(:short)
  .media-body                                
    h5.media-heading.user_name 
      = comment.user.name
      =< comment.user.last_name
    = simple_format(comment.content) 

app/views/comments/_form.slim
.container
br
  = form_for(Comment.new , url: post_comments_path(@post)) do |f|
    .form-group.row
      .col-sm-12
        = f.text_area :content, class: "form-control", placeholder: "Comment"      
    .btn-group.btn-group  
      = button_tag(type: 'submit', class: "btn btn-success") do
        .icon-ok.icon-white  = t('buttons.comments.save')

app/views/layouts/_message.slim
- flash.each do |type, message|
  div class="alert #{bootstrap_flash_class(type)} fade in" 
    = message

app/views/layouts/application.slim
doctype html
html
  head
    title Users
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags
  
body
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
          span.sr-only 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to  t('app_name'), root_path, class: 'navbar-brand'
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          - if can? :create, User
            li = link_to ' All Users', users_path
          - if user_signed_in?
            li = link_to t('buttons.posts.create'), new_post_path
            li.dropdown
              = link_to "#{current_user.name} #{current_user.last_name}",
                        edit_user_registration_path(current_user), 
                         class: 'dropdown-toggle', aria: { expanded:"false" , haspopup:"true"}, 
                        data: { toggle:"dropdown" },  role: "button" 
              ul.dropdown-menu
                li = link_to t('links.users.edit_profile'), 
                            edit_user_registration_path(current_user)
                li = link_to 'Logout', destroy_user_session_path, :method => :delete
          - else
            li 
              = link_to 'Login', new_user_session_path
            li 
              = link_to 'Sign up', new_user_registration_path                        
  .container  
    = render partial: 'layouts/message'
    = yield
  #footer.panel-footer
    .container

app/views/posts/_form.slim
.container
  = form_for(@post) do |f|
    - if @post.errors.any?
      .alert.alert-danger
        error_explanation
          h2
            = pluralize(@post.errors.count, t('errors.error')) 
            = t('errors.save_post')
          ul
          - @post.errors.full_messages.each do |message|
            li = message

    .form-group.row
      = f.label :title, class: 'col-sm-1 col-form-label'
      .col-sm-8
        = f.text_field :title, autofocus: true, class: "form-control", placeholder: 'Title'      
    .form-group.row
      = f.label :content, class: 'col-sm-1 col-form-label'
      .col-sm-8
        = f.cktext_area :content, class: 'form-control'
    .form-group.row
      .preview-container
        = f.label :image, class: 'col-sm-1 col-form-label'
        .thumbnail.image-preview-container.col-xs-6.col-md-3.preview
          = cl_image_tag @post.image,  id: 'img_prev', :crop => :fill 
        .col-sm-8.col-sm-offset-1
          = f.file_field :image, class: 'filestyle'
    br
    br  
    = button_tag(type: 'submit', class: 'btn btn-success btn-space') do
      .icon-ok.icon-white  = t('buttons.posts.save')
      
    = link_to  t('buttons.posts.back'), posts_path, class: 'btn btn-warning'

app/views/posts/_like.slim
= link_to  vote_post_path(post), {remote: true, method: :put, class: 'btn btn-default', id: post.id} do
  span
    i.fa.fa-heart-o
  =< post.get_upvotes.size
end

app/views/posts/_post.slim
.grid-item
  figure.effect-marley
    = link_to post do 
      = cl_image_tag post.image, :crop => :fill
      figcaption
        h2  ="#{post.title} "
        p ="#{post.user.name} #{post.user.last_name}"      
    end
  .row.like-button
    = render partial: 'like', locals: { post: post }

app/views/posts/edit.slim
= render 'form'

app/views/posts/index.slim
.grid
  .grid-sizer
  = render partial: 'post', collection: @posts || t('errors.no_posts')

app/views/posts/new.slim
= render 'form' 

app/views/posts/show.js.erb
$('#comments').append('<%= j render @comments %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @comments %>');
  $('.pagination').hide();
  // $('.preload').hide();
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
  $('.preload').remove();
<% end %>

app/views/posts/show.slim
h4
  .image
    .thumbnail.image-preview-container
      = cl_image_tag @post.image,  :crop => :fill 
    h5#image 
      span 
        ="#{t('posts.attr.title')}: #{@post.title} "
      br
      span ="#{t('posts.attr.author')}: #{@post.user.name} #{@post.user.last_name}"
h4
  strong = t('posts.attr.content')
  =< raw(@post.content)    
- if can? :update, @post
  = link_to t('buttons.posts.edit'), edit_post_path(@post), class: 'btn btn-success btn-space'
  = link_to t('links.posts.destroy'), @post, method: :delete, 
    data: { confirm: 'Are you sure?' },  class: 'btn btn-danger btn-space'
= link_to t('buttons.posts.back'), posts_path, class: 'btn btn-warning'
= render 'comments/form'  
- if @post.comments.present?
  .container
    .row
      .col-md-12
        .page-header
          h3 = t('labels.comments')
        #comments.comments-list
          = render partial: 'comments/comment', collection: @comments                         

#infinite-scrolling
  = will_paginate @comments
  .preload.row.center
    i.fa.fa-cog.fa-spin.fa-3x.fa-fw

app/views/posts/vote.js.erb
$("#<%= @post.id%>").bind('ajax:success', function() {
  $(this).parent().html("<%= escape_javascript(render 'like', post: @post) %>");
});

app/views/users/_form.slim
.container

  = form_for(@user) do |f|
    - if @user.errors.any?
      .alert.alert-danger
        error_explanation
          h2
            = pluralize(@user.errors.count, t('errors.error')) 
            = t('errors.save_user')
          ul
          - @user.errors.full_messages.each do |message|
            li = message

    .form-group.row
      = f.label :name, class: 'col-sm-1 col-form-label'
      .col-sm-4
        = f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name'      
    .form-group.row
      = f.label :last_name, class: 'col-sm-1 col-form-label'
      .col-sm-4
        = f.text_field :last_name, class: 'form-control', placeholder: 'Last Name'
    .form-group.row
      = f.label :email, class: 'col-sm-1 col-form-label'
      .col-sm-4
        = f.text_field :email, class: 'form-control', placeholder: 'Email'
    .form-group.row
      = f.label :age, class: 'col-sm-1 col-form-label'
      .col-sm-4
        = f.number_field :age, class: 'form-control', placeholder: 'Age'
    .form-group.row
      = f.label :password, class: 'col-sm-1 col-form-label'
      - if @minimum_password_length
        em 
          | (
          = @minimum_password_length
          |  characters minimum )
      .col-sm-4
        = f.password_field :password, autocomplete: 'off', class: 'form-control', placeholder: 'Password' 
    br
    br  
    = button_tag(type: 'submit', class: 'btn btn-success btn-space') do
      .icon-ok.icon-white = t('buttons.users.save')
      
    = link_to t('buttons.users.back'), users_path, class: 'btn btn-warning'

app/views/users/_user.slim
tr
  td
    = user.name
  td
    = user.last_name  
  td
    = user.email
  td
    = user.age
  td
    = link_to t('links.users.show'), user
  td
    = link_to t('links.users.edit'), edit_user_path(user)
  td
    = link_to t('links.users.destroy'), user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/index.slim
.col.align-self-center
  table class='table table-condensed'
    thead
      tr
        th = t('users.attr.name')
        th = t('users.attr.last_name')
        th = t('users.attr.email')
        th = t('users.attr.age')
        th colspan="3"
    tbody
      = render partial: 'user', collection: @users || t('errors.no_users')
      
  = link_to t('buttons.users.create'), new_user_path, class: 'btn btn-success' 

app/views/users/show.slim
h4
  strong Name:
  =< @user.name  
h4
  strong Last Name:
  =< @user.last_name
h4
  strong Email:
  =< @user.email
h4
  strong Age:
  =< @user.age
    

= link_to t('buttons.users.edit'), edit_user_path(@user), class: 'btn btn-success btn-space'
= link_to t('buttons.users.back'), users_path, class: 'btn btn-warning'